### ISSUE TITLE
Post Title as SLUG?

### ISSUE THREAD

**Issue by xingzhong** [gschier/simple-blog#4]
FIrst of all, this is great package. Simple and clean. Exactly what I want. 

From my understanding, the system using post title as SLUG parameter to identify the post.
Can we use integer number, since the title could be anything. For example, I want using Chinese.

**Comment by gschier** [comment]
I'm glad you like the package. An integer counter is one possible solution, but it requires keeping track of a global counter somewhere in the system. How do you feel about using the 10 digit unix timestamp as a slug? That would be the easiest solution to implement, however the urls wouldn't be as pretty as a simple counter.

**Comment by xingzhong** [comment]
Right. Timestamp is better than counter. If 10 digits is too much, we could even try hash it to a even short form.

**Comment by gschier** [comment]
A short form hash would be good. If you convert the timestamp to base 36 you end up with 6 character string, which is short enough to not look terrible in my opinion.

Example: 1360209376 => MHU09S

**Comment by gschier** [comment]
Found a base conversion library to use https://npmjs.org/package/bases

**Comment by gschier** [comment]
Just pushed the feature to NPM. That was easier than I thought.
