### ISSUE TITLE
Post editing 404's

### ISSUE THREAD

**Issue by rwoody** [gschier/simple-blog#8]
I'm trying to access a post to test the editing functionality. The documentation says to hit:

/edit/posts/<POST SLUG>

My example, for instance:

http://localhost:5000/edit/posts/better-blogging-with-node-mongodb-and-backbone

**Comment by rwoody** [comment]
The documentation was wrong.

It said:

edit post     `/edit/posts/<POST SLUG>`

But should be `/edit/post/<POST SLUG>`

**Comment by gschier** [comment]
Thanks for pointing that out! :grinning:
